# Generated by Django 5.1.3 on 2024-11-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canban', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddField(
            model_name='grade',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canban.result'),
        ),
        migrations.AddField(
            model_name='status',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.direction'),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_authored', to='crm.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.direction'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_users',
            field=models.ManyToManyField(related_name='responsible_users', to='crm.profile'),
        ),
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canban.task'),
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canban.task'),
        ),
        migrations.AddField(
            model_name='customization',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='canban.task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='canban.task'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='canban.task'),
        ),
    ]
