# Generated by Django 5.1.3 on 2024-11-22 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=1000, verbose_name='Ваш текст')),
            ],
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('count', models.IntegerField(default=0, verbose_name='Количество задач,выполненных в срок')),
                ('rating', models.FloatField(verbose_name='Средний рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название универститета')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('count', models.IntegerField(verbose_name='Количество баллов за вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='App_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Заявка одобрена?')),
                ('comment', models.CharField(max_length=1000, verbose_name='Отзыв')),
                ('test_count', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на организационный чат')),
                ('start', models.DateField(auto_now=True)),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_authored', to='crm.profile')),
                ('curators', models.ManyToManyField(related_name='curated_projects', to='crm.profile')),
                ('students', models.ManyToManyField(related_name='student_projects', to='crm.profile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_projects', to='crm.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на организационный чат')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('count', models.IntegerField(verbose_name='Полученный балл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Организатор', 'Организатор'), ('Руководитель', 'Руководитель'), ('Куратор', 'Куратор'), ('Тимлид', 'Тимлид'), ('Разработчик', 'Разработчик'), ('Аналитик', 'Аналитик'), ('Дизайнер', 'Дизайнер')], default='На согласовании', max_length=50, verbose_name='Название роли')),
                ('users', models.ManyToManyField(related_name='users', to='crm.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='crm.skill'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='crm.profile')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.direction')),
                ('students', models.ManyToManyField(to='crm.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('entry', models.IntegerField(verbose_name='Порог прохождения в %')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.test'),
        ),
        migrations.CreateModel(
            name='True_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question')),
            ],
        ),
    ]
