# Generated by Django 5.1.3 on 2025-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
